# Generated by Django 4.0.1 on 2022-01-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='body_en',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='slug_en',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='title_en',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='body_fa',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='slug_fa',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='title_fa',
        ),
        migrations.AddField(
            model_name='articles',
            name='lang',
            field=models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], default='fa', max_length=10),
        ),
    ]
