# Generated by Django 4.0.1 on 2022-01-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_body_en_articles_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='lang',
            field=models.CharField(choices=[('fa', 'fa'), ('en', 'en')], max_length=10),
        ),
    ]
