# Generated by Django 4.0.1 on 2022-01-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_articles_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlescategory',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='articlescategory',
            name='title_fa',
        ),
        migrations.AddField(
            model_name='articlescategory',
            name='lang',
            field=models.CharField(choices=[('fa', 'fa'), ('en', 'en')], default='fa', max_length=10),
        ),
        migrations.AddField(
            model_name='articlescategory',
            name='title',
            field=models.CharField(default='a', max_length=100),
        ),
    ]
