# Generated by Django 4.0.1 on 2022-01-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_articlescategory_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlescategory',
            name='lang',
            field=models.CharField(choices=[('fa', 'fa'), ('en', 'en')], max_length=10),
        ),
        migrations.AlterField(
            model_name='articlescategory',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
